version: '3.8'
services:
  frontend:
    build:
      context: ./usecases/browser_RTMedAgent/frontend
      dockerfile: Dockerfile
    env_file:
      - ./usecases/browser_RTMedAgent/frontend/.env
    ports:
      - "5173:5173"

  # Be sure to run the devtunnel if developing locally
  # and to update the root .env file with the tunnel URL
  backend:
    build:
      context: ./
      dockerfile: ./usecases/browser_RTMedAgent/backend/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8010:8010"